language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  - ./prepare-runtime-env.sh
script:
  - ls
